FROM nginx

COPY conf.d/default.conf /etc/nginx/conf.d/default.conf

COPY certs/map_minecraft-wildhunt_com.crt /etc/ssl/certs/map_minecraft-wildhunt_com.crt
COPY certs/map_minecraft-wildhunt_com.key /etc/ssl/private/map_minecraft-wildhunt_com.key
